// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doctors.sql

package sqlc

import (
	"context"
)

const findDoctors = `-- name: FindDoctors :many
SELECT
    d.id::text AS id,
    d.specialty_id::text AS specialty_id,
    d.clinic_id::text AS clinic_id,
    d.full_name
FROM doctors d
WHERE
    (
        $1::text = ''
        OR d.id = NULLIF($1::text, '')::uuid
    )
    AND (
        $2::text = ''
        OR d.clinic_id = NULLIF($2::text, '')::uuid
    )
    AND (
        $3::text = ''
        OR EXISTS (
            SELECT 1
            FROM visits v
            WHERE v.doctor_id = d.id
              AND v.id = NULLIF($3::text, '')::uuid
        )
    )
ORDER BY d.full_name, d.id
`

type FindDoctorsParams struct {
	DoctorID string
	ClinicID string
	VisitID  string
}

type FindDoctorsRow struct {
	ID          string
	SpecialtyID string
	ClinicID    string
	FullName    string
}

func (q *Queries) FindDoctors(ctx context.Context, arg FindDoctorsParams) ([]FindDoctorsRow, error) {
	rows, err := q.db.Query(ctx, findDoctors, arg.DoctorID, arg.ClinicID, arg.VisitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindDoctorsRow
	for rows.Next() {
		var i FindDoctorsRow
		if err := rows.Scan(
			&i.ID,
			&i.SpecialtyID,
			&i.ClinicID,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
