// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: elasticsearch_sync.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVisitForElasticsearchSync = `-- name: GetVisitForElasticsearchSync :one
SELECT
    v.id::text AS id,
    v.doctor_id::text AS doctor_id,
    v.patient_id::text AS patient_id,
    v.clinic_id::text AS clinic_id,
    v.status,
    v.visit_start_time,
    v.visit_end_time,
    v.created_at,
    v.updated_at,
    d.specialty_id::text AS doctor_specialty_id,
    d.clinic_id::text AS doctor_clinic_id,
    d.full_name AS doctor_full_name,
    p.first_name AS patient_first_name,
    p.last_name AS patient_last_name,
    p.date_of_birth AS patient_date_of_birth,
    p.gender AS patient_gender,
    p.is_deleted AS patient_is_deleted,
    c.name AS clinic_name,
    c.address AS clinic_address,
    c.time_zone AS clinic_time_zone
FROM visits v
JOIN doctors d ON d.id = v.doctor_id
JOIN patients p ON p.id = v.patient_id
JOIN clinics c ON c.id = v.clinic_id
WHERE v.id = $1
`

type GetVisitForElasticsearchSyncRow struct {
	ID                 string
	DoctorID           string
	PatientID          string
	ClinicID           string
	Status             string
	VisitStartTime     pgtype.Timestamptz
	VisitEndTime       pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DoctorSpecialtyID  string
	DoctorClinicID     string
	DoctorFullName     string
	PatientFirstName   string
	PatientLastName    string
	PatientDateOfBirth pgtype.Date
	PatientGender      string
	PatientIsDeleted   pgtype.Bool
	ClinicName         string
	ClinicAddress      string
	ClinicTimeZone     string
}

func (q *Queries) GetVisitForElasticsearchSync(ctx context.Context, visitID pgtype.UUID) (GetVisitForElasticsearchSyncRow, error) {
	row := q.db.QueryRow(ctx, getVisitForElasticsearchSync, visitID)
	var i GetVisitForElasticsearchSyncRow
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.PatientID,
		&i.ClinicID,
		&i.Status,
		&i.VisitStartTime,
		&i.VisitEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DoctorSpecialtyID,
		&i.DoctorClinicID,
		&i.DoctorFullName,
		&i.PatientFirstName,
		&i.PatientLastName,
		&i.PatientDateOfBirth,
		&i.PatientGender,
		&i.PatientIsDeleted,
		&i.ClinicName,
		&i.ClinicAddress,
		&i.ClinicTimeZone,
	)
	return i, err
}

const listClinicsForElasticsearchSync = `-- name: ListClinicsForElasticsearchSync :many
SELECT
    id::text AS id,
    name,
    address,
    time_zone,
    created_at,
    updated_at
FROM clinics
WHERE id = ANY($1::uuid[])
ORDER BY id
`

type ListClinicsForElasticsearchSyncRow struct {
	ID        string
	Name      string
	Address   string
	TimeZone  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListClinicsForElasticsearchSync(ctx context.Context, clinicIds []pgtype.UUID) ([]ListClinicsForElasticsearchSyncRow, error) {
	rows, err := q.db.Query(ctx, listClinicsForElasticsearchSync, clinicIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClinicsForElasticsearchSyncRow
	for rows.Next() {
		var i ListClinicsForElasticsearchSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.TimeZone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoctorsForElasticsearchSync = `-- name: ListDoctorsForElasticsearchSync :many
SELECT
    id::text AS id,
    specialty_id::text AS specialty_id,
    clinic_id::text AS clinic_id,
    full_name,
    created_at,
    updated_at
FROM doctors
WHERE id = ANY($1::uuid[])
ORDER BY id
`

type ListDoctorsForElasticsearchSyncRow struct {
	ID          string
	SpecialtyID string
	ClinicID    string
	FullName    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListDoctorsForElasticsearchSync(ctx context.Context, doctorIds []pgtype.UUID) ([]ListDoctorsForElasticsearchSyncRow, error) {
	rows, err := q.db.Query(ctx, listDoctorsForElasticsearchSync, doctorIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDoctorsForElasticsearchSyncRow
	for rows.Next() {
		var i ListDoctorsForElasticsearchSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.SpecialtyID,
			&i.ClinicID,
			&i.FullName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientsForElasticsearchSync = `-- name: ListPatientsForElasticsearchSync :many
SELECT
    id::text AS id,
    first_name,
    last_name,
    date_of_birth,
    gender,
    is_deleted,
    created_at,
    updated_at
FROM patients
WHERE id = ANY($1::uuid[])
ORDER BY id
`

type ListPatientsForElasticsearchSyncRow struct {
	ID          string
	FirstName   string
	LastName    string
	DateOfBirth pgtype.Date
	Gender      string
	IsDeleted   pgtype.Bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListPatientsForElasticsearchSync(ctx context.Context, patientIds []pgtype.UUID) ([]ListPatientsForElasticsearchSyncRow, error) {
	rows, err := q.db.Query(ctx, listPatientsForElasticsearchSync, patientIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatientsForElasticsearchSyncRow
	for rows.Next() {
		var i ListPatientsForElasticsearchSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DateOfBirth,
			&i.Gender,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitSummariesForElasticsearchSync = `-- name: ListVisitSummariesForElasticsearchSync :many
SELECT
    v.id::text AS id,
    v.doctor_id::text AS doctor_id,
    v.patient_id::text AS patient_id,
    p.first_name AS patient_first_name,
    p.last_name AS patient_last_name,
    v.clinic_id::text AS clinic_id,
    v.status,
    v.visit_start_time,
    v.visit_end_time,
    v.created_at,
    v.updated_at
FROM visits v
JOIN patients p ON p.id = v.patient_id
WHERE v.doctor_id = ANY($1::uuid[])
   OR v.patient_id = ANY($2::uuid[])
   OR v.clinic_id = ANY($3::uuid[])
ORDER BY v.visit_start_time, v.id
`

type ListVisitSummariesForElasticsearchSyncParams struct {
	DoctorIds  []pgtype.UUID
	PatientIds []pgtype.UUID
	ClinicIds  []pgtype.UUID
}

type ListVisitSummariesForElasticsearchSyncRow struct {
	ID               string
	DoctorID         string
	PatientID        string
	PatientFirstName string
	PatientLastName  string
	ClinicID         string
	Status           string
	VisitStartTime   pgtype.Timestamptz
	VisitEndTime     pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) ListVisitSummariesForElasticsearchSync(ctx context.Context, arg ListVisitSummariesForElasticsearchSyncParams) ([]ListVisitSummariesForElasticsearchSyncRow, error) {
	rows, err := q.db.Query(ctx, listVisitSummariesForElasticsearchSync, arg.DoctorIds, arg.PatientIds, arg.ClinicIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisitSummariesForElasticsearchSyncRow
	for rows.Next() {
		var i ListVisitSummariesForElasticsearchSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.PatientID,
			&i.PatientFirstName,
			&i.PatientLastName,
			&i.ClinicID,
			&i.Status,
			&i.VisitStartTime,
			&i.VisitEndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
