// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: elasticsearch_backfill.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listClinicsForElasticsearchBackfill = `-- name: ListClinicsForElasticsearchBackfill :many
SELECT
    id::text AS id,
    name,
    address,
    time_zone,
    created_at,
    updated_at
FROM clinics
ORDER BY id
`

type ListClinicsForElasticsearchBackfillRow struct {
	ID        string
	Name      string
	Address   string
	TimeZone  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListClinicsForElasticsearchBackfill(ctx context.Context) ([]ListClinicsForElasticsearchBackfillRow, error) {
	rows, err := q.db.Query(ctx, listClinicsForElasticsearchBackfill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClinicsForElasticsearchBackfillRow
	for rows.Next() {
		var i ListClinicsForElasticsearchBackfillRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.TimeZone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoctorsForElasticsearchBackfill = `-- name: ListDoctorsForElasticsearchBackfill :many
SELECT
    id::text AS id,
    specialty_id::text AS specialty_id,
    clinic_id::text AS clinic_id,
    full_name,
    created_at,
    updated_at
FROM doctors
ORDER BY id
`

type ListDoctorsForElasticsearchBackfillRow struct {
	ID          string
	SpecialtyID string
	ClinicID    string
	FullName    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListDoctorsForElasticsearchBackfill(ctx context.Context) ([]ListDoctorsForElasticsearchBackfillRow, error) {
	rows, err := q.db.Query(ctx, listDoctorsForElasticsearchBackfill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDoctorsForElasticsearchBackfillRow
	for rows.Next() {
		var i ListDoctorsForElasticsearchBackfillRow
		if err := rows.Scan(
			&i.ID,
			&i.SpecialtyID,
			&i.ClinicID,
			&i.FullName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientsForElasticsearchBackfill = `-- name: ListPatientsForElasticsearchBackfill :many
SELECT
    id::text AS id,
    first_name,
    last_name,
    date_of_birth,
    gender,
    is_deleted,
    created_at,
    updated_at
FROM patients
ORDER BY id
`

type ListPatientsForElasticsearchBackfillRow struct {
	ID          string
	FirstName   string
	LastName    string
	DateOfBirth pgtype.Date
	Gender      string
	IsDeleted   pgtype.Bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListPatientsForElasticsearchBackfill(ctx context.Context) ([]ListPatientsForElasticsearchBackfillRow, error) {
	rows, err := q.db.Query(ctx, listPatientsForElasticsearchBackfill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatientsForElasticsearchBackfillRow
	for rows.Next() {
		var i ListPatientsForElasticsearchBackfillRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DateOfBirth,
			&i.Gender,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitsForElasticsearchBackfill = `-- name: ListVisitsForElasticsearchBackfill :many
SELECT
    v.id::text AS id,
    v.doctor_id::text AS doctor_id,
    v.patient_id::text AS patient_id,
    v.clinic_id::text AS clinic_id,
    v.status,
    v.visit_start_time,
    v.visit_end_time,
    v.created_at,
    v.updated_at,
    d.specialty_id::text AS doctor_specialty_id,
    d.clinic_id::text AS doctor_clinic_id,
    d.full_name AS doctor_full_name,
    p.first_name AS patient_first_name,
    p.last_name AS patient_last_name,
    p.date_of_birth AS patient_date_of_birth,
    p.gender AS patient_gender,
    p.is_deleted AS patient_is_deleted,
    c.name AS clinic_name,
    c.address AS clinic_address,
    c.time_zone AS clinic_time_zone
FROM visits v
JOIN doctors d ON d.id = v.doctor_id
JOIN patients p ON p.id = v.patient_id
JOIN clinics c ON c.id = v.clinic_id
ORDER BY v.visit_start_time, v.id
`

type ListVisitsForElasticsearchBackfillRow struct {
	ID                 string
	DoctorID           string
	PatientID          string
	ClinicID           string
	Status             string
	VisitStartTime     pgtype.Timestamptz
	VisitEndTime       pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DoctorSpecialtyID  string
	DoctorClinicID     string
	DoctorFullName     string
	PatientFirstName   string
	PatientLastName    string
	PatientDateOfBirth pgtype.Date
	PatientGender      string
	PatientIsDeleted   pgtype.Bool
	ClinicName         string
	ClinicAddress      string
	ClinicTimeZone     string
}

func (q *Queries) ListVisitsForElasticsearchBackfill(ctx context.Context) ([]ListVisitsForElasticsearchBackfillRow, error) {
	rows, err := q.db.Query(ctx, listVisitsForElasticsearchBackfill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisitsForElasticsearchBackfillRow
	for rows.Next() {
		var i ListVisitsForElasticsearchBackfillRow
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.PatientID,
			&i.ClinicID,
			&i.Status,
			&i.VisitStartTime,
			&i.VisitEndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DoctorSpecialtyID,
			&i.DoctorClinicID,
			&i.DoctorFullName,
			&i.PatientFirstName,
			&i.PatientLastName,
			&i.PatientDateOfBirth,
			&i.PatientGender,
			&i.PatientIsDeleted,
			&i.ClinicName,
			&i.ClinicAddress,
			&i.ClinicTimeZone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
