// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Patient struct {
	ID          pgtype.UUID
	FirstName   string
	LastName    string
	DateOfBirth pgtype.Date
	Gender      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	IsDeleted   pgtype.Bool
	DeletedAt   pgtype.Timestamptz
}
