// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Clinic struct {
	ID        pgtype.UUID
	Name      string
	Address   string
	TimeZone  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Doctor struct {
	ID          pgtype.UUID
	SpecialtyID pgtype.UUID
	FullName    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ClinicID    pgtype.UUID
}

type Patient struct {
	ID          pgtype.UUID
	FirstName   string
	LastName    string
	DateOfBirth pgtype.Date
	Gender      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	IsDeleted   pgtype.Bool
	DeletedAt   pgtype.Timestamptz
}

type Specialty struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
