// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (
    aggregate_type,
    aggregate_id,
    event_type,
    payload
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateOutboxEventParams struct {
	AggregateType string
	AggregateID   pgtype.UUID
	EventType     string
	Payload       []byte
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const listPendingOutboxEventsForUpdate = `-- name: ListPendingOutboxEventsForUpdate :many
SELECT
    candidate.id,
    candidate.aggregate_type,
    candidate.aggregate_id,
    candidate.event_type,
    candidate.payload,
    candidate.created_at,
    candidate.processed_at,
    candidate.event_sequence
FROM outbox_events AS candidate
WHERE candidate.processed_at IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM outbox_events AS earlier
      WHERE earlier.aggregate_type = candidate.aggregate_type
        AND earlier.aggregate_id = candidate.aggregate_id
        AND earlier.processed_at IS NULL
        AND earlier.event_sequence < candidate.event_sequence
  )
ORDER BY candidate.event_sequence
LIMIT $1::int
FOR UPDATE OF candidate SKIP LOCKED
`

func (q *Queries) ListPendingOutboxEventsForUpdate(ctx context.Context, batchSize int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEventsForUpdate, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.EventSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :execrows
UPDATE outbox_events
SET processed_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND processed_at IS NULL
`

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxEventProcessed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
