// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (
    aggregate_type,
    aggregate_id,
    event_type,
    payload
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateOutboxEventParams struct {
	AggregateType string
	AggregateID   pgtype.UUID
	EventType     string
	Payload       []byte
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	return err
}
