// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findPatients = `-- name: FindPatients :many
SELECT
    id::text AS id,
    first_name,
    last_name,
    date_of_birth::text AS date_of_birth,
    gender,
    is_deleted
FROM patients
WHERE is_deleted = false
    AND (
        $1::text = ''
        OR id = NULLIF($1::text, '')::uuid
    )
    AND (
        $2::text = ''
        OR id <> NULLIF($2::text, '')::uuid
    )
    AND (
        $3::text = ''
        OR first_name ILIKE '%' || $3::text || '%'
    )
    AND (
        $4::text = ''
        OR last_name ILIKE '%' || $4::text || '%'
    )
ORDER BY
    CASE
        WHEN $5::text = 'first_name'
            AND $6::text = 'asc'
        THEN first_name
    END ASC,
    CASE
        WHEN $5::text = 'first_name'
            AND $6::text = 'desc'
        THEN first_name
    END DESC,
    CASE
        WHEN $5::text = 'last_name'
            AND $6::text = 'asc'
        THEN last_name
    END ASC,
    CASE
        WHEN $5::text = 'last_name'
            AND $6::text = 'desc'
        THEN last_name
    END DESC,
    CASE
        WHEN $5::text = 'date_of_birth'
            AND $6::text = 'asc'
        THEN date_of_birth
    END ASC,
    CASE
        WHEN $5::text = 'date_of_birth'
            AND $6::text = 'desc'
        THEN date_of_birth
    END DESC,
    CASE
        WHEN $5::text = 'created_at'
            AND $6::text = 'asc'
        THEN created_at
    END ASC,
    CASE
        WHEN $5::text = 'created_at'
            AND $6::text = 'desc'
        THEN created_at
    END DESC,
    created_at DESC,
    id ASC
LIMIT $8::int
OFFSET $7::bigint
`

type FindPatientsParams struct {
	EqualsID      string
	NotEqualsID   string
	FirstName     string
	LastName      string
	SortField     string
	SortDirection string
	PageOffset    int64
	PageLimit     int32
}

type FindPatientsRow struct {
	ID          string
	FirstName   string
	LastName    string
	DateOfBirth string
	Gender      string
	IsDeleted   pgtype.Bool
}

func (q *Queries) FindPatients(ctx context.Context, arg FindPatientsParams) ([]FindPatientsRow, error) {
	rows, err := q.db.Query(ctx, findPatients,
		arg.EqualsID,
		arg.NotEqualsID,
		arg.FirstName,
		arg.LastName,
		arg.SortField,
		arg.SortDirection,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPatientsRow
	for rows.Next() {
		var i FindPatientsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DateOfBirth,
			&i.Gender,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
