// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findPatients = `-- name: FindPatients :many
SELECT
    id::text AS id,
    first_name,
    last_name,
    date_of_birth::text AS date_of_birth,
    gender,
    is_deleted
FROM patients
WHERE is_deleted = false
    AND (
        $1::uuid IS NULL
        OR id = $1::uuid
    )
    AND (
        $2::uuid IS NULL
        OR id <> $2::uuid
    )
    AND (
        $3::text IS NULL
        OR first_name ILIKE '%' || $3::text || '%'
    )
    AND (
        $4::text IS NULL
        OR last_name ILIKE '%' || $4::text || '%'
    )
ORDER BY created_at DESC
`

type FindPatientsParams struct {
	EqualsID    pgtype.UUID
	NotEqualsID pgtype.UUID
	FirstName   pgtype.Text
	LastName    pgtype.Text
}

type FindPatientsRow struct {
	ID          string
	FirstName   string
	LastName    string
	DateOfBirth string
	Gender      string
	IsDeleted   pgtype.Bool
}

func (q *Queries) FindPatients(ctx context.Context, arg FindPatientsParams) ([]FindPatientsRow, error) {
	rows, err := q.db.Query(ctx, findPatients,
		arg.EqualsID,
		arg.NotEqualsID,
		arg.FirstName,
		arg.LastName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPatientsRow
	for rows.Next() {
		var i FindPatientsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DateOfBirth,
			&i.Gender,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
