// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visits.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVisit = `-- name: CreateVisit :one
INSERT INTO visits (
    doctor_id,
    patient_id,
    clinic_id,
    visit_start_time,
    visit_end_time
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id::text AS id,
    doctor_id::text AS doctor_id,
    patient_id::text AS patient_id,
    clinic_id::text AS clinic_id,
    status,
    visit_start_time,
    visit_end_time,
    created_at,
    updated_at
`

type CreateVisitParams struct {
	DoctorID       pgtype.UUID
	PatientID      pgtype.UUID
	ClinicID       pgtype.UUID
	VisitStartTime pgtype.Timestamptz
	VisitEndTime   pgtype.Timestamptz
}

type CreateVisitRow struct {
	ID             string
	DoctorID       string
	PatientID      string
	ClinicID       string
	Status         string
	VisitStartTime pgtype.Timestamptz
	VisitEndTime   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (CreateVisitRow, error) {
	row := q.db.QueryRow(ctx, createVisit,
		arg.DoctorID,
		arg.PatientID,
		arg.ClinicID,
		arg.VisitStartTime,
		arg.VisitEndTime,
	)
	var i CreateVisitRow
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.PatientID,
		&i.ClinicID,
		&i.Status,
		&i.VisitStartTime,
		&i.VisitEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVisit = `-- name: DeleteVisit :one
DELETE FROM visits
WHERE id = $1
RETURNING id::text
`

func (q *Queries) DeleteVisit(ctx context.Context, visitID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, deleteVisit, visitID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getVisitStatusForUpdate = `-- name: GetVisitStatusForUpdate :one
SELECT status
FROM visits
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetVisitStatusForUpdate(ctx context.Context, visitID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getVisitStatusForUpdate, visitID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listVisits = `-- name: ListVisits :many
SELECT
    id::text AS id,
    doctor_id::text AS doctor_id,
    patient_id::text AS patient_id,
    clinic_id::text AS clinic_id,
    status,
    visit_start_time,
    visit_end_time,
    created_at,
    updated_at
FROM visits
ORDER BY visit_start_time ASC, id ASC
LIMIT $2::int
OFFSET $1::bigint
`

type ListVisitsParams struct {
	PageOffset int64
	PageLimit  int32
}

type ListVisitsRow struct {
	ID             string
	DoctorID       string
	PatientID      string
	ClinicID       string
	Status         string
	VisitStartTime pgtype.Timestamptz
	VisitEndTime   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListVisits(ctx context.Context, arg ListVisitsParams) ([]ListVisitsRow, error) {
	rows, err := q.db.Query(ctx, listVisits, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisitsRow
	for rows.Next() {
		var i ListVisitsRow
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.PatientID,
			&i.ClinicID,
			&i.Status,
			&i.VisitStartTime,
			&i.VisitEndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVisit = `-- name: UpdateVisit :one
UPDATE visits
SET
    doctor_id = COALESCE($1, doctor_id),
    patient_id = COALESCE($2, patient_id),
    clinic_id = COALESCE($3, clinic_id),
    visit_start_time = COALESCE($4, visit_start_time),
    visit_end_time = COALESCE($5, visit_end_time),
    status = COALESCE($6, status),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $7
RETURNING
    id::text AS id,
    doctor_id::text AS doctor_id,
    patient_id::text AS patient_id,
    clinic_id::text AS clinic_id,
    status,
    visit_start_time,
    visit_end_time,
    created_at,
    updated_at
`

type UpdateVisitParams struct {
	DoctorID       pgtype.UUID
	PatientID      pgtype.UUID
	ClinicID       pgtype.UUID
	VisitStartTime pgtype.Timestamptz
	VisitEndTime   pgtype.Timestamptz
	Status         pgtype.Text
	VisitID        pgtype.UUID
}

type UpdateVisitRow struct {
	ID             string
	DoctorID       string
	PatientID      string
	ClinicID       string
	Status         string
	VisitStartTime pgtype.Timestamptz
	VisitEndTime   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateVisit(ctx context.Context, arg UpdateVisitParams) (UpdateVisitRow, error) {
	row := q.db.QueryRow(ctx, updateVisit,
		arg.DoctorID,
		arg.PatientID,
		arg.ClinicID,
		arg.VisitStartTime,
		arg.VisitEndTime,
		arg.Status,
		arg.VisitID,
	)
	var i UpdateVisitRow
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.PatientID,
		&i.ClinicID,
		&i.Status,
		&i.VisitStartTime,
		&i.VisitEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
