// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visits.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVisit = `-- name: CreateVisit :one
INSERT INTO visits (
    doctor_id,
    patient_id,
    clinic_id,
    visit_start_time,
    visit_end_time
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id::text AS id,
    doctor_id::text AS doctor_id,
    patient_id::text AS patient_id,
    clinic_id::text AS clinic_id,
    visit_start_time,
    visit_end_time,
    created_at,
    updated_at
`

type CreateVisitParams struct {
	DoctorID       pgtype.UUID
	PatientID      pgtype.UUID
	ClinicID       pgtype.UUID
	VisitStartTime pgtype.Timestamptz
	VisitEndTime   pgtype.Timestamptz
}

type CreateVisitRow struct {
	ID             string
	DoctorID       string
	PatientID      string
	ClinicID       string
	VisitStartTime pgtype.Timestamptz
	VisitEndTime   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (CreateVisitRow, error) {
	row := q.db.QueryRow(ctx, createVisit,
		arg.DoctorID,
		arg.PatientID,
		arg.ClinicID,
		arg.VisitStartTime,
		arg.VisitEndTime,
	)
	var i CreateVisitRow
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.PatientID,
		&i.ClinicID,
		&i.VisitStartTime,
		&i.VisitEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
